### ISSUE TITLE
Criar diagrama de classes

### ISSUE THREAD

**Issue by FabricaAppU9** [FabricaAppU9/ProSpiro#2]

**Comment by matheusopedro** [comment]
A criação do Diagrama de classes foi iniciada pelo Alexandre e o Jonathan.

Caminho do arquivo do diagrama no drive:

01. Projeto Espirometria > Documentação > ProSpiro > Modelagem > Diagrama de Classes

**Comment by matheusopedro** [comment]
Diagrama de classes criado.

Link no drive.
https://drive.google.com/drive/folders/0B3rkYCGAcDhARFlPbmhFMnJwd00?usp=sharing
